# Generated by Django 4.2.17 on 2025-03-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_type', models.CharField(choices=[('PG', 'PG'), ('Room', 'Room')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_title', models.CharField(max_length=100)),
                ('room_size', models.CharField(blank=True, max_length=50, null=True)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('bathroom_type', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_tenants', models.CharField(blank=True, max_length=50, null=True)),
                ('features', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_details', models.CharField(blank=True, max_length=50, null=True)),
                ('image1', models.CharField(blank=True, max_length=256, null=True)),
                ('image2', models.CharField(blank=True, max_length=256, null=True)),
                ('image3', models.CharField(blank=True, max_length=256, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_me.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_me.user'),
        ),
        migrations.CreateModel(
            name='PGDetails',
            fields=[
                ('pg_id', models.AutoField(primary_key=True, serialize=False)),
                ('pg_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('meal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_tenants', models.CharField(blank=True, max_length=50, null=True)),
                ('features', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_details', models.CharField(blank=True, max_length=50, null=True)),
                ('image1', models.CharField(blank=True, max_length=256, null=True)),
                ('image2', models.CharField(blank=True, max_length=256, null=True)),
                ('image3', models.CharField(blank=True, max_length=256, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_me.property')),
            ],
        ),
    ]
